REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50333, 1, 0, 'You have woken the bull, no face the horns!', 12, 0, 100, 0, 0, 0, 'Lon the bull - SAY_AGGRO');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50344, 3, 0, 'Your end is near.', 12, 0, 100, 0, 0, 0, 'Norlaxx - SAY-AGGRO');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50791, 4, 0, 'I will wear your skin as a hat!', 12, 0, 100, 0, 0, 0, 'Siltriss - SAY_AGGRO');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50820, 2, 0, 'I must give in to the anger! It is the only way!', 12, 0, 100, 0, 0, 0, 'Yul Wildpaw - SAY_AGGRO');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50832, 7, 0, 'You has ook for brains!', 12, 0, 100, 0, 0, 0, 'The Yowler - SAY_AGGRO');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50355, 0, 0, 'The torture of a thousand screaming deaths awaits...', 12, 0, 100, 0, 0, 0, 'Kah\'tir - SAY_AGGRO');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50734, 5, 0, 'My brethren are endless in number.', 12, 0, 100, 0, 0, 0, 'Lith\'ik - SAY_AGGRO');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (50772, 6, 0, 'The waters speak of your demise...', 12, 0, 100, 0, 0, 0, 'Eshelon - SAY_AGGRO');

